In [3]:
import numpy as np

In [4]:

numbers = np.array([121,122,399])
letters = np.array(["A","B"])

# enumerate: obtiene indice y valor
for index, value in enumerate(numbers):
    print(index,value)

# zip: itera en 2 lista a la vez
for v1, v2 in zip(numbers,letters):
    print(v1,v2)

# reversed: iterar una lista al reves
for v in reversed(numbers):
    print(v)


0 121
1 122
2 399
121 A
122 B
399
122
121


In [5]:
# funcion puede devolver mas de un valor

def multiple(a,b):
    return a+b, a-b

x1,x2 = multiple(1,2)
print(x1,x2)

#funciones anonimas
multBy2 = lambda x: 2*x
multBy2(2)

sum = lambda x,y: x*y
sum(2,3)



# yield: sigue devolviendo los valores y los almacena en una lista
def func():
    for i in range(10):
        if i%2:
            yield i

gen = func()
for i in gen:
    print(i)

gen = (i for i in range(10)  if i % 2)
for i in gen:
    print(i)



3 -1
1
3
5
7
9
1
3
5
7
9


1. Cada dimensión se denomina **_axis_**
2. El número de dimensiones se denomina **_rank_**
3. La lista de dimensiones con su correspondiente longitud se denomina **_shape_**
4. El número total de elementos se denomina **_size_**

In [6]:
a = np.zeros((2,4))
a 
# 2 axis -> Longitud 2 y Longitud 4
# rank   -> 2
# shape  -> (2,4) 
# size   -> 8
a.shape
a.ndim
a.size

b = np.zeros((1,3,5))
b

c = np.ones((2,3,4))
c

d = np.full((2,3,4),8)
d

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [7]:
e = np.array([[1,2,3],[1,2,3]])
e.ndim

f = np.linspace(0,6,10) # 10 elementos del 0 al 6 proporcionales
f

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [11]:
array_uni = np.array([1,2,3,4,5,6])
print(array_uni.shape)
print(array_uni)
type(array_uni)

print(array_uni[0])
print(array_uni[2:4])
print(array_uni[0::2])


(6,)
[1 2 3 4 5 6]
1
[3 4]
[1 3 5]


In [9]:
array_multi = np.array([[1,2,3],[4,5,6]])
print(array_multi.shape)

# Las filas y columnas comienzan del índice cero

print(array_multi[1,2]) 
print(array_multi[0,2])

print(array_multi[0,:])
print(array_multi[1,:])
print(array_multi[:,0])
print(array_multi[:,1])
print(array_multi[:,2])

print(array_multi[0:2,2])
print(array_multi[0:2,1])
print(array_multi[0:2,0])


(2, 3)
6
3
[1 2 3]
[4 5 6]
[1 4]
[2 5]
[3 6]
[3 6]
[2 5]
[1 4]


In [15]:
reshape_array = np.arange(28)
reshape_array
print(reshape_array.reshape((7,4)))
print("----------------")
print(reshape_array.reshape((28,1)))
print("----------------")
print(reshape_array.reshape((2,1,14)))
print("----------------")
print(reshape_array.reshape((14,2)))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
----------------
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]]
----------------
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20 21 22 23 24 25 26 27]]]
----------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]]
